### ISSUE TITLE
Problema con cambiar la version de node con nvm (Mac)

### ISSUE THREAD

**Issue by piacabrera** [IIC2513-2022/syllabus-2#1]
Hola! cuando trato de correr la aplicación con "yarn start" me aparece el error "The engine "node" is incompatible with this module. Expected version "10.x || 12.x". Got "17.8.0"" , el problema es que al tratar de cambiar la versión de node con "nvm use 12", me aparece "Now using node v12.22.11 (npm v8.5.5)", pero si corro "nvm current node -v", me tira "system". Es como si no cambiara la version de node, a pesar de intentarlo con nvm. 

Les agradeceria si alguien me puede ayudar  :)

**Comment by valeeeriquelme** [comment]
Solucionado. Se ocupó lo [siguiente](https://github.com/nvm-sh/nvm/issues/1184#issuecomment-438347276), sugerido en una [issue](https://github.com/nvm-sh/nvm/issues/1184) con el problema similar.
