### ISSUE TITLE
[Interrogación 1] Parte 2, duda sobre manejo de tipo de datos

### ISSUE THREAD

**Issue by burgosibarra** [IIC2513-2022/syllabus-2#10]
Hola!
Cuando nos dicen que se verifiquen que "los números SEAN números" entiendo que algunos atributos que deberían ser de tipo 'number' no necesariamente lo sean. Pero ¿cuántos casos deberíamos abordar? ¿Pueden entregarnos un string de la forma "páginas 15"? ¿o un array de la forma "[15]" ?

**Comment by valeeeriquelme** [comment]
Hola, ¿Esta pregunta es acerca de la forma 2 cierto? no entiendo mucho tu pregunta. Siempre les vamos a entregar un arreglo con la estructura que aparece en el enunciado, lo que va a cambiar es el valor asociado a cada key...por ejemplo, les podríamos pasar página:ocho (en uno de los objetos del array), eso lo tendrían que detectar como un no número.

**Comment by danielauu** [comment]
¿en el caso que diga 'ocho', tendríamos que tratarlo como un 8, ignoramos el dato o lanzamos algún error?

**Comment by valeeeriquelme** [comment]
@burgosibarra en los ejemplos que indicas ninguno es un número (atributo página me refiero), por lo que todos deberían ser controlados como un error en el tipo de dato. 

Fíjate bien en como se pasan los datos en el ejemplo. El arreglo de objetos que esperamos que "pase" y se ejecute correctamente debe seguir el mismo formato.

**Comment by burgosibarra** [comment]
perfecto, gracias!
