### ISSUE TITLE
[Interrogacion 1] [Parte 2] Modificar array o hacer una copia nueva

### ISSUE THREAD

**Issue by sopadeoliva** [IIC2513-2022/syllabus-2#11]
Hola! En la parte de "agregarDensidad" es necesario retornar una copia del array arrPais modificada, o se modifica el array directamente? Porque he estado usando funciones para copiar arrays pero no me funcionan por alguna razon :(

**Comment by HernanCabrera** [comment]
Lo relevante es que retorne un arreglo con la estructura solicitada no tanto si el arreglo queda o no en su estado original o modificado pues lo que e comprobará es que el arreglo retornado por la función cumpla con tener todos los datos incluido el "nuevo"
