### ISSUE TITLE
[INTERROGACIÓN 1][FORMA 1] Sobre los datos de los objRegion

### ISSUE THREAD

**Issue by based-on-what** [IIC2513-2022/syllabus-2#12]
Hola, en el enunciado en su forma 1, sobre los **objRegion**, muestran ejemplos de estos objetos en el array **arrPais**, sin embargo, lo que muestran no está completo, hago esta pregunta, porque buscando en google, hay una discrepancia entre lo que muestra el enunciado y lo que se obtiene en internet, por ejemplo, en el enunciado, dice que la población de la región de Arica y Parinacota es de 225000 habitantes, pero en el sitio del [gobierno](https://www.gob.cl/regiones/region-de-arica-y-parinacota/#:~:text=La%20regi%C3%B3n%20cuenta%20con%20una,acuerdo%20al%20Censo%20de%202017.) sale que son 226068 habitantes, solo por eso me caen dudas sobre dónde buscar los datos de las regiones que faltan en el array de ejemplo, ¿o podemos usar cualquier dato oficial mientras esté citado?

Saludos y muchas gracias.

**Comment by HernanCabrera** [comment]
Los datos son irrelevantes, es solo un ejemplo. 
Lo que probaremos es que funcione. Es mas, eso se aclara en el mismo enunciado e incluso usaremos arreglos con datos aleatorios. Lo importante es que se sume correctamente todo lo que se deba sumar, que haga los calculos de densidad de manera adecuada, etc. Si es 250.000 o 275.000 no importa, pero si la funcion recibe 3 regiones con 20.000, lo que nos importa es que la suma sea 60.000
Espero se entienda (en el enunciado sale este criterio para mayor detalle en la explicacion)

**Comment by based-on-what** [comment]
> Los datos son irrelevantes, es solo un ejemplo. Lo que probaremos es que funcione. Es mas, eso se aclara en el mismo enunciado e incluso usaremos arreglos con datos aleatorios. Lo importante es que se sume correctamente todo lo que se deba sumar, que haga los calculos de densidad de manera adecuada, etc. Si es 250.000 o 275.000 no importa, pero si la funcion recibe 3 regiones con 20.000, lo que nos importa es que la suma sea 60.000 Espero se entienda (en el enunciado sale este criterio para mayor detalle en la explicacion)

Gracias por la respuesta, me di cuenta al poco rato de haber hecho la issue, pero no como no sabía cómo borrarla, la mantuve jaja, saludos!
