### ISSUE TITLE
[Interrogacion 1] [Parte 3] Unico archivo main.js (?

### ISSUE THREAD

**Issue by yuwet15** [IIC2513-2022/syllabus-2#13]
Todo el backend estará en ese unico archivo main.js o podemos crear otros archivos?

**Comment by HernanCabrera** [comment]
El main.js será el archivo que se ejecutará con node. Dado que el proyecto es pequeñito, (un endpoint obligatorio, dos como máximo) se da la facilidad de tener un único archivo llamado main.js (para diferenciarlo de index.js que será usado en front) Ahora bien, si desea y por buenas prácticas. puede tener varios archivos Js que sean coordinados desde main.js, no es problema.
Debe indicar eso en su README así como la estructura de directorios adecuada para ejecutarlo. Lo único a considerar es que será  main.js el que usaremos para levantar la aplicación, como dice el enunciado.

Saludos y éxito

**Comment by yuwet15** [comment]
ok, muchas gracias por la aclaración
