### ISSUE TITLE
Duda con endpoint "get"

### ISSUE THREAD

**Issue by piacabrera** [IIC2513-2022/syllabus-2#14]
Hola! me entro una duda dado que en el enunciado especifican que el endpoint debe ser get, y que podemos entregar la información con body y un Jason, pero en archivo index.js al intentar con method get y un body obtengo "Unhandled Promise Rejection: TypeError: Request has method 'GET' and cannot have a body", lo cual no me ocurre con el post por ejemplo. Que podría hacer en este caso para entregar un body?

**Comment by valeeeriquelme** [comment]
Hola, el error que mencionas está bien que ocurra y es parte del contenido que debieran manejar. Con una búsqueda rápida en internet encontrarás lo que está pasando. 

De todas formas, aclaro que cuando se habla de entregar información con un body, se refiere a la respuesta desde el backend. Para enviar información desde el front, te recomiendo revisar el uso de params.

Espero haber respondido tu pregunta ✌️

**Comment by HernanCabrera** [comment]
No puede usar POST. El POST no se debe usar para este caso pues es solo para requerir información.

Para aclarar el enunciado y complementar la respuesta dada por Valeria, porque puedo ver en la redacción donde se induce el error:

Usted debe invocar el GET y pasar parámetros en la invocación de la url que usará el fetch. Y allí usted deberá modelar sus parámetros para que sean recibidos en el back.

La respuesta también la puede modelar como usted desee y la entrega en el body para que luego al enviarla de vuelta (response) la procese en el cliente como respuesta al fetch

y el Json? pues bien, su decisión de diseño como formar el JSON.

Saludos

**Comment by piacabrera** [comment]
Perfecto! me quedo super claro muchas gracias
