### ISSUE TITLE
[Interrogacion 1] [Parte 3] Pregunta de enunciado

### ISSUE THREAD

**Issue by v4rgas** [IIC2513-2022/syllabus-2#15]
La API debe recibir todos los ingredientes y devolver el resultado o recibir un ingrediente y devolver el resultado de este para luego sumarlos en el frontend?

**Comment by HernanCabrera** [comment]
Como dijo al principio Usted, la API recibe todos los ingredientes y devuelve el resultado.

Usted puede diseñar el mensaje que se enviará al back de la forma que desee

**Comment by v4rgas** [comment]
gracias
