### ISSUE TITLE
[Interrogacion 1] [Parte 3] Pregunta de enunciado corta

### ISSUE THREAD

**Issue by matias-berrios-o** [IIC2513-2022/syllabus-2#16]
En el enunciado se pide "Un archivo index.js con el código javascript a ejecutar en el front." En vez de eso, se puede dejar el código de javascript en el mismo HTML (index.html)?

**Comment by matias-berrios-o** [comment]
Aprovecho de agregar otra pregunta... El boton de descuento puede aplicarse cuantas veces sea por cotizacion? O luego de la primera vez, este boton queda disfuncional?

**Comment by HernanCabrera** [comment]
Para la segunda pregunta: El botón de descuento no tiene un comportamiento definido, puede dejarlo deshabilitado si desea, sólo se probará que funcione una vez, lo otro es un adicional

Para la primera pregunta, eso es una mala práctica que en clases de cátedra se ha recalcado en varias ocasiones.

Saludos
