### ISSUE TITLE
[Interrogación 1 - Forma 2 - Parte 2] Buenas prácticas: escritura variables y parámetros

### ISSUE THREAD

**Issue by gustavoselman** [IIC2513-2022/syllabus-2#17]
Hola, respecto a las buenas prácticas quería saber si en JavaScript se pueden escribir variables y parámetros de funciones en **snake case** (ej: arreglo_nuevo) o debe ser en **camel case** (ej: arregloNuevo) ?

Quedo atento.

**Comment by HernanCabrera** [comment]
La recomendación es camel case

Saludos.

**Comment by gustavoselman** [comment]
Okay, gracias.
