### ISSUE TITLE
[Interrogación 1][Parte 2] agregaValoracion

### ISSUE THREAD

**Issue by galanfd** [IIC2513-2022/syllabus-2#18]
Hola! Para esta función que tipo de errores tenemos que manejar? Se me ocurren unos ejemplos: 
En el caso de que la pagina no sea un numero se le tiene que agregar valoración igual?
En el caso de que la valoración de un libro no sea número se agrega igual?
Se tiene que manejar si es que el largo del array arrValoración no es el mismo que el arrBiblioteca?
Gracias!

**Comment by HernanCabrera** [comment]
Los errores mínimos, para esta parte, se indican en el enunciado.
- La pagina y otros errores de tipo de datos no tienen que ver con el proceso de asignar una valoración, así que si se valora.
- los errores de tipo de datos se validan y se declara el error (retornaría un código de error que usted defina y debe documentarlo
-  Sobre los arreglos, no tienen que ser del mismo largo, en el caso que no sean del mismo largo la opción es valorar lo que se puede y el resto de los objLibro pueden quedar con algún codigo numérico que indique que no tiene valoración
