### ISSUE TITLE
Error: Unable to connect to the database: ConnectionError [SequelizeConnectionError]

### ISSUE THREAD

**Issue by aiarias** [IIC2513-2022/syllabus-2#2]
Hola!, segui el paso a paso de la capsula y la wiki para instalar el template para el proyecto. Pero al momento de probar que funciona (yarn start) me sale el error Unable to connect to the database: ConnectionError [SequelizeConnectionError], y no logro abrir el proyecto en browser, y no logro saber que podra ser. (Todo esto en Ubuntu)

**Comment by valeeeriquelme** [comment]
Hola!
Porfavor adjunta un pantallazo del error y de tus archivos (indicando dónde están tus variables de entorno). 

Además, si me puedes indicar que soluciones ya has intentando.

**Comment by raimundomartinez** [comment]
Hola! Tengo exactamente el mismo problema, solo que igual al final de todo me sale "Compiled successfully". Si me conecto a localhost:3000 me sale que no se encuentra nada, pero si me conecto a localhost:53065 por lo menos me se una página en donde sale "upgrade required". Las lineas del terminal son las siguientes:
![Captura de Pantalla 2022-04-12 a la(s) 21 25 28](https://user-images.githubusercontent.com/48482564/163080981-d47f55f6-bf8c-4339-a2b2-588ec871f6a8.png)
![Captura de Pantalla 2022-04-12 a la(s) 21 25 32](https://user-images.githubusercontent.com/48482564/163080977-3b5aa878-77a0-4057-8692-c94743e198e7.png)

**Comment by gonzaloconcha** [comment]
Te aparece un mensaje diciendo **rol "myuser" does not exist**. Fíjate bien que definas bien tus variables y credenciales para la base de datos. Estas deben ser las correctas con los permisos necesarios.

**Comment by raimundomartinez** [comment]
No entiendo. En la cápsula de template nunca hacemos nada con la base de datos, lo único que hacemos es crear un archivo .env con lo siguiente:

DB_NAME=mydatabase
DB_USERNAME=myuser
DB_PASSWORD=mypassword

Seguí la cápsula al pie de la letra en 3 computadores distintos. Según yo le falta un paso a la cápsula 1, probablemente relacionado con la creación/configuración de la base de datos.

**Comment by valeeeriquelme** [comment]
Hola,
Cómo se indica en la cápsula (y en el readme de esta), esas credenciales hacen referencia a un usuario y base de datos que se creó previamente. Debes usar tus propias credenciales en esta parte. 

La configuración de la base de datos no es parte del alcance de la cápsula del template. 

Por mientras, puedes encontrar en internet material para hacer la configuración de la base de datos (crear usuario y base de datos). De todas formas, durante la semana subiremos una cápsula anexa sobre el tema, para apoyarlos/as/es por si llegaran a quedar consultas.
