### ISSUE TITLE
[INTERROGACIÓN 1][PARTE 2, FORMA 1] Sobre agregaDensidad

### ISSUE THREAD

**Issue by based-on-what** [IIC2513-2022/syllabus-2#21]
Hola, como la función `agregaDensidad` tiene como uno de sus parámetros a `arrDensidad`, que es el arreglo que retorna `densidad`, ¿podemos asumir que el arreglo de la densidad ya pasó por el manejo de errores y todos los valores del arreglo están "bien" en cuanto a los tipos de su contenido? ¿O hay que manejar los errores de tipo de datos ahí `(agregaDensidad)` también?

Saludos

**Comment by hernancabrerap** [comment]
si, puede ser. Dejelo especificado en el Readme. 
Eso es para los tipos de datos, lo que si puede seguir siendo un problema es que los largos no coincidan.... Pero de eso se habló en otros issues
