### ISSUE TITLE
[Interrogación 1][Parte 3] Variable de entorno

### ISSUE THREAD

**Issue by yuwet15** [IIC2513-2022/syllabus-2#23]
Hola, quería consultar si por parte del front también es necesario usar el .env

**Comment by hernancabrerap** [comment]
Claro que no. en cátedra se explicó que el broswer por construcción, está incapacitado para acceder a los recursos del computador donde se ejecuta, por lo tanto no puede abrir archivos directamente y eso redunda en que no se pueden dejar archivos de configuración como .env u otros

**Comment by yuwet15** [comment]
Muchas gracias por la aclaración
