### ISSUE TITLE
[Interrogacion 1 - Parte 2 - Forma 2] Arreglo de valoracion

### ISSUE THREAD

**Issue by martin-iturralde** [IIC2513-2022/syllabus-2#24]
Hola,
Podemos asumir que este arreglo siempre contendrá números? No otros tipos. 
Es decir:
arr = [1,2,3,4] Así
arr = [1,2,3, '4'] Y, no así. 
arr = [1,2,3, 'cuatro' ] Y, no así.

**Comment by hernancabrerap** [comment]
No, no siempre contendrá números, es más, en el enunciado se describe los tipos de errores que se deberán controlar. en particular el control de tipo de datos

**Comment by martin-iturralde** [comment]
Ok! Pero, el enunciado no dice de este array en específico. Y, en el caso que no sean números se agregan igual a la volaración?

**Comment by hernancabrerap** [comment]
en las notas dice esta regla de tipo general: (2) Se verificará que ustedes, en sus funciones, controlen (cuando sea necesario) la división por cero y el tipo de datos (en particular que los números SEAN números) 
Esto aplica para todos los casos y en particular para el arreglo de su pregunta.
