### ISSUE TITLE
[Interrogación 1] [Forma 2] [Parte 3] Agrandar

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2513-2022/syllabus-2#26]
Hola!

Tengo la duda si en la parte 3 de la forma 2 se pide hacer descuento como sale en el enunciado o mas un impuesto por agrandar, ya que en el ejemplo es un incremento de precio y tiene más sentido que sea así.

Gracias de antemano!

**Comment by valeeeriquelme** [comment]
Es lo que tu dices, funciona aumentando el valor final

**Comment by Jamesmoreno21** [comment]
Muchas gracias!!
