### ISSUE TITLE
Error Sequelize

### ISSUE THREAD

**Issue by gonzaga2000** [IIC2513-2022/syllabus-2#4]
Hola! cuando hago yarn start me tira el siguiente error:
![Captura de pantalla 2022-05-09 224857](https://user-images.githubusercontent.com/80769344/167533754-bfc76281-c799-420a-97f1-a930234098db.jpg)
He probado cambiando la contrasena y me sigue diciendo lo mismo, alguna forma de solucionarlo?

**Comment by valeeeriquelme** [comment]
Hola, y a través de la command line de postgres puedes usar ese usuario y contraseña y crear una bdd? Te pregunto para saber si es un tema de postgres o de cómo definiste las variables de entorno

**Comment by gonzaga2000** [comment]
reinice postgres y funciono!
